language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  # "pypy2.7"
  - "pypy3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libepr-api-dev

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -U unittest2; fi
  - python setup.py build_ext --inplace

script: make PYTHON=python check
