language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libepr-api-dev

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION < '3.4' ]]; then pip install -U unittest2; fi
  - python setup.py build_ext --inplace

script: make PYTHON=python check
