language: python

python:
  - 2.6
  - 2.7
  - "2.7_with_system_site_packages"
  - 3.2
  - "3.2_with_system_site_packages"
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libepr-api2-dev
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -U unittest2; fi

install: python setup.py build_ext --inplace

script: make PYTHON=python check
