language: python

virtualenv:
  system_site_packages: true

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libepr-api2-dev
  - pip install -r requirements.txt --use-mirrors

install: python setup.py build_ext --inplace

script: make PYTHON=python check
