language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy3"

matrix:
  allow_failures:
    - python: "pypy3"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libepr-api-dev

install:
  - pip install -r requirements-dev.txt
  - pip install sphinx coverage codecov
  - if [[ $TRAVIS_PYTHON_VERSION = 'pypy3' ]]; then pip install -U numpy cython; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION = '3.8' ]]; then make PYTHON=python coverage; else make PYTHON=python check; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION = '3.8' ]]; then codecov; fi
